---
title: "PSTAT 194cs Final Project"
author: "Tingting Liang"
date: "2024-06-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(dplyr)
library(igraph)
library(igraphdata)
library(Matrix)
library(jsonlite)
library(ape)
```

```{r}
# define margins
no_marg <- c(0, 0, 0, 0)
def_marg <- c(5.1, 4.1, 4.1, 2.1)
```

# Load Data
```{r}
## load the data
congress_twi.edgelist <- read.table("./data/congress.edgelist", sep = " ", header = TRUE, stringsAsFactors = FALSE)
data <- fromJSON('./data/congress_network_data.json')
node_attr <- read.csv('./data/congress_twitter_node_attributes.csv')
region <- read.csv('./data/us_regions.csv')
region <- region[, c(2,3)]
names(region)[names(region) == 'State.Code'] <- 'State'
node_attr = left_join(node_attr, region, by = 'State')

## subset without the weight
EL <- subset(congress_twi.edgelist, select = c(1, 2))
## Convert Network Edge Data to 'igraph' Object
congress_twi.edgelist <- matrix(unlist(EL),ncol=2)+1 # plus 1 to index from 1
## turn it into igraph
congress_twi.igraph <- graph.edgelist((congress_twi.edgelist))
```

# Add Attributes
```{r}
## add username as an attribute
# Extract the data
usernameList <- data[]$usernameList[[1]]
congress_twi.igraph <- set_vertex_attr(congress_twi.igraph, "username", value = usernameList)
# verify length
length(V(congress_twi.igraph)$username)

## add name of each person as an attribute
congressperson <- node_attr[]$Congressperson
congress_twi.igraph <- set_vertex_attr(congress_twi.igraph, "congressperson", value = congressperson)
# verify
length(V(congress_twi.igraph)$congressperson)

## add chamber as attribute
chamber <- node_attr[]$Chamber
congress_twi.igraph <- set_vertex_attr(congress_twi.igraph, "chamber", value = chamber)
# verify
length(V(congress_twi.igraph)$chamber)

## add party as attribute
party <- node_attr[]$Party
congress_twi.igraph <- set_vertex_attr(congress_twi.igraph, "party", value = party)
# verify
length(V(congress_twi.igraph)$party)

## add state as attributes
state <- node_attr[]$State
congress_twi.igraph <- set_vertex_attr(congress_twi.igraph, "state", value = state)
# verify
length(V(congress_twi.igraph)$state)

## add region as attributes
region <- node_attr[]$Region
congress_twi.igraph <- set_vertex_attr(congress_twi.igraph, "region", value = region)
# verify
length(V(congress_twi.igraph)$region)

vertex_attr_names(congress_twi.igraph)
```


# Four induced sub-graphs with 200 random nodes each
```{r}
sub.network1 <- induced_subgraph(congress_twi.igraph, sample(V(congress_twi.igraph), 75))

sub.network2 <- induced_subgraph(congress_twi.igraph, sample(V(congress_twi.igraph), 75))

sub.network3 <- induced_subgraph(congress_twi.igraph, sample(V(congress_twi.igraph), 75))

sub.network4 <- induced_subgraph(congress_twi.igraph, sample(V(congress_twi.igraph), 75))
```

# Subgraph Plots
## Subgraph 1
```{r}
sen_maj_leader <- "Chuck Shumer"
sen_min_leader <- "Mitch McConnell"
house_speaker <- "Nancy Pelosi"
house_maj_leader <- "Steny Hoyer"
house_min_leader <- "Kevin McCarthy"

dem_leaders <- c(sen_maj_leader, house_speaker, house_min_leader)
rep_leaders <- c(sen_min_leader, house_min_leader)
leaders <- c(dem_leaders, rep_leaders)

# Intra-party Interactions

und_subnetwork1 <- as.undirected(sub.network1) 
deg1 <- igraph::degree(sub.network1, mode="all")
V(sub.network1)$deg1 <- deg1

# Color Parties
V(und_subnetwork1)[V(und_subnetwork1)$party == 'R']$color <- "red"
V(und_subnetwork1)[V(und_subnetwork1)$party == 'D']$color <- "blue"
V(und_subnetwork1)[V(und_subnetwork1)$party == 'I']$color <- "yellow"

# Color Congressional Leaders
V(und_subnetwork1)[V(und_subnetwork1)$congressperson %in% leaders]$frame.color <- "gold"

# Label Colors
V(und_subnetwork1)[(V(und_subnetwork1)$party == 'R') | (V(und_subnetwork1)$party == 'D')]$label.color <- "white"
V(und_subnetwork1)[V(und_subnetwork1)$party == "I"]$label.color <- "black"

# Color Edges
E(und_subnetwork1)$color <- "gray70"
E(und_subnetwork1)[(V(und_subnetwork1)$party == 'R') %--% (V(und_subnetwork1)$party == 'D')]$color <- "purple3"

par(mar = no_marg)
plot(
  und_subnetwork1,
  layout = layout_with_kk(und_subnetwork1),
  vertex.size = deg1/2,
  vertex.frame.width = 3,
  vertex.label.cex = 0.5,
  vertex.label.family = "Helvetica",
  vertex.shape = "circle",
  vertex.label.color = V(und_subnetwork1)$label.color,
  edge.width = 2
)
```

```{r}
table(V(und_subnetwork1)$region)

regioncolors <- c('Midwest'='purple', 'Northeast'='pink', 'South'='skyblue', 'West'='gold')
regionlabels <- c('Midwest'='black', 'Northeast'='black', 'South'='black', 'West'='black')
V(und_subnetwork1)$color <- regioncolors[V(und_subnetwork1)$region]
V(und_subnetwork1)$frame.color <- regioncolors[V(und_subnetwork1)$region]
V(und_subnetwork1)$label.color <- regionlabels[V(und_subnetwork1)$region]

E(und_subnetwork1)$color <- "blue"
E(und_subnetwork1)[(V(und_subnetwork1)$region == 'Midwest') %--% (V(und_subnetwork1)$region == 'Midwest')]$color <- "purple"
E(und_subnetwork1)[(V(und_subnetwork1)$region == 'Northeast') %--% (V(und_subnetwork1)$region == 'Northeast')]$color <- "pink"
E(und_subnetwork1)[(V(und_subnetwork1)$region == 'South') %--% (V(und_subnetwork1)$region == 'South')]$color <- "skyblue"
E(und_subnetwork1)[(V(und_subnetwork1)$region == 'West') %--% (V(und_subnetwork1)$region == 'West')]$color <- "gold"

par(mar=no_marg)
plot(und_subnetwork1,
    layout=layout_in_circle(und_subnetwork1),
    vertex.size = 8,
    vertex.label.cex = 0.5,
    vertex.label.family = 'Helvetica',
    vertex.frame.color = V(und_subnetwork1)$color,
    vertex.label.color = V(und_subnetwork1)$label.color,
    edge.width = 1,
    edge.arrow.size = 0.1)
```

```{r}
# Inter-chamber/Intra-chamber Interactions

# Color Chambers
V(und_subnetwork1)[V(und_subnetwork1)$chamber == "Senate"]$color <- "gold"
V(und_subnetwork1)[V(und_subnetwork1)$chamber == "House"]$color <- "dodgerblue"

# Color Party Leaders
V(und_subnetwork1)[V(und_subnetwork1)$congressperson %in% dem_leaders]$color <- "blue"
V(und_subnetwork1)[V(und_subnetwork1)$congressperson %in% rep_leaders]$color <- "red"

# Set Label Colors
V(und_subnetwork1)[V(und_subnetwork1)$chamber == "Senate"]$label.color <- "black"
V(und_subnetwork1)[V(und_subnetwork1)$chamber == "House"]$label.color <- "gray99"


# Set Edge Colors by Interaction
E(und_subnetwork1)$color <- "darkgreen"
E(und_subnetwork1)[(V(und_subnetwork1)$chamber == 'Senate') %--% (V(und_subnetwork1)$chamber == 'Senate')]$color <- "gold"
E(und_subnetwork1)[(V(und_subnetwork1)$chamber == 'House') %--% (V(und_subnetwork1)$chamber == 'House')]$color <- "lightskyblue"


par(mar = no_marg)
plot(
  und_subnetwork1,
  layout = layout_on_grid(und_subnetwork1),
  vertex.size = 7,
  vertex.label.cex = 0.65,
  vertex.label.family = "Helvetica",
  vertex.color = V( und_subnetwork1)$color,
  vertex.shape = "circle",
  vertex.frame.color = "gray50",
  vertex.label.color = V(und_subnetwork1)$label.color,
  edge.width = 1,
  edge.curved = 0.2,
)
```
## Subgraph 2
```{r}
deg2 <- igraph::degree(sub.network2, mode="all")
V(sub.network1)$deg2 <- deg2

und_subnetwork2 <- as.undirected(sub.network2)
sen_maj_leader <- "Chuck Shumer"
sen_min_leader <- "Mitch McConnell"
house_speaker <- "Nancy Pelosi"
house_maj_leader <- "Steny Hoyer"
house_min_leader <- "Kevin McCarthy"

dem_leaders <- c(sen_maj_leader, house_speaker, house_min_leader)
rep_leaders <- c(sen_min_leader, house_min_leader)
leaders <- c(dem_leaders, rep_leaders)

# Intra-party Interactions
 
# Color Parties
V(und_subnetwork2)[V(und_subnetwork2)$party == 'R']$color <- "red"
V(und_subnetwork2)[V(und_subnetwork2)$party == 'D']$color <- "blue"
V(und_subnetwork2)[V(und_subnetwork2)$party == 'I']$color <- "yellow"

# Color Congressional Leaders
V(und_subnetwork2)[V(und_subnetwork2)$congressperson %in% leaders]$frame.color <- "gold"

# Label Colors
V(und_subnetwork2)[(V(und_subnetwork2)$party == 'R') | (V(und_subnetwork2)$party == 'D')]$label.color <- "white"
V(und_subnetwork2)[V(und_subnetwork2)$party == "I"]$label.color <- "black"

# Color Edges
E(und_subnetwork2)$color <- "gray70"
E(und_subnetwork2)[(V(und_subnetwork2)$party == 'R') %--% (V(und_subnetwork2)$party == 'D')]$color <- "purple3"

par(mar = no_marg)
plot(
  und_subnetwork2,
  layout = layout_with_kk(und_subnetwork2),
  vertex.size = deg2/2,
  vertex.frame.width = 3,
  vertex.label.cex = 0.8,
  vertex.label.family = "Helvetica",
  vertex.shape = "circle",
  vertex.label.color = V(und_subnetwork2)$label.color,
  edge.width = 2
)
```
```{r}
# Inter-chamber/Intra-chamber Interactions

# Color Chambers
V(und_subnetwork2)[V(und_subnetwork2)$chamber == "Senate"]$color <- "gold"
V(und_subnetwork2)[V(und_subnetwork2)$chamber == "House"]$color <- "dodgerblue"

# Color Party Leaders
V(und_subnetwork2)[V(und_subnetwork2)$congressperson %in% dem_leaders]$color <- "blue"
V(und_subnetwork2)[V(und_subnetwork2)$congressperson %in% rep_leaders]$color <- "red"

# Set Label Colors
V(und_subnetwork2)[V(und_subnetwork2)$chamber == "Senate"]$label.color <- "black"
V(und_subnetwork2)[V(und_subnetwork2)$chamber == "House"]$label.color <- "gray99"


# Set Edge Colors by Interaction
E(und_subnetwork2)$color <- "darkgreen"
E(und_subnetwork2)[(V(und_subnetwork2)$chamber == 'Senate') %--% (V(und_subnetwork2)$chamber == 'Senate')]$color <- "gold"
E(und_subnetwork2)[(V(und_subnetwork2)$chamber == 'House') %--% (V(und_subnetwork2)$chamber == 'House')]$color <- "lightskyblue"


par(mar = no_marg)
plot(
  und_subnetwork2,
  layout = layout_on_grid(und_subnetwork2),
  vertex.size = 7,
  vertex.label.cex = 0.65,
  vertex.label.family = "Helvetica",
  vertex.color = V(und_subnetwork2)$color,
  vertex.shape = "circle",
  vertex.frame.color = "gray50",
  vertex.label.color = V(und_subnetwork2)$label.color,
  edge.width = 1,
  edge.curved = 0.2,
)
```
```{r}
und_subnetwork2 <- as.undirected(sub.network2)
table(V(und_subnetwork2)$region)

regioncolors <- c('Midwest'='purple', 'Northeast'='pink', 'South'='skyblue', 'West'='gold')
regionlabels <- c('Midwest'='black', 'Northeast'='black', 'South'='black', 'West'='black')
V(und_subnetwork2)$color <- regioncolors[V(und_subnetwork2)$region]
V(und_subnetwork2)$frame.color <- regioncolors[V(und_subnetwork2)$region]
V(und_subnetwork2)$label.color <- regionlabels[V(und_subnetwork2)$region]

V(und_subnetwork2)$region[is.na(V(und_subnetwork2)$region)] <- "None"

E(und_subnetwork2)$color <- "blue"
E(und_subnetwork2)[(V(und_subnetwork2)$region == 'Midwest') %--% (V(und_subnetwork2)$region == 'Midwest')]$color <- "purple"
E(und_subnetwork2)[(V(und_subnetwork2)$region == 'Northeast') %--% (V(und_subnetwork2)$region == 'Northeast')]$color <- "pink"
E(und_subnetwork2)[(V(und_subnetwork2)$region == 'South') %--% (V(und_subnetwork2)$region == 'South')]$color <- "skyblue"
E(und_subnetwork2)[(V(und_subnetwork2)$region == 'West') %--% (V(und_subnetwork2)$region == 'West')]$color <- "gold"

par(mar=no_marg)
plot(und_subnetwork2,
    layout=layout_in_circle(und_subnetwork2),
    vertex.size = 8,
    vertex.label.cex = 0.5,
    vertex.label.family = 'Helvetica',
    vertex.frame.color = V(und_subnetwork2)$color,
    vertex.label.color = V(und_subnetwork2)$label.color,
    edge.width = 1,
    edge.arrow.size = 0.1)
```
## Subgraph 3
```{r}
und_subnetwork3 <- as.undirected(sub.network3)
deg3 <- igraph::degree(sub.network3, mode="all")
V(sub.network3)$deg3 <- deg3

sen_maj_leader <- "Chuck Shumer"
sen_min_leader <- "Mitch McConnell"
house_speaker <- "Nancy Pelosi"
house_maj_leader <- "Steny Hoyer"
house_min_leader <- "Kevin McCarthy"

dem_leaders <- c(sen_maj_leader, house_speaker, house_min_leader)
rep_leaders <- c(sen_min_leader, house_min_leader)
leaders <- c(dem_leaders, rep_leaders)

# Inter-party Interactions
 
# Color Parties
V(und_subnetwork3)[V(und_subnetwork3)$party == 'R']$color <- "red"
V(und_subnetwork3)[V(und_subnetwork3)$party == 'D']$color <- "blue"
V(und_subnetwork3)[V(und_subnetwork3)$party == 'I']$color <- "yellow"

# Color Congressional Leaders
V(und_subnetwork3)[V(und_subnetwork3)$congressperson %in% leaders]$frame.color <- "gold"

# Label Colors
V(und_subnetwork3)[(V(und_subnetwork3)$party == 'R') | (V(und_subnetwork3)$party == 'D')]$label.color <- "white"
V(und_subnetwork3)[V(und_subnetwork3)$party == "I"]$label.color <- "black"

# Color Edges
E(und_subnetwork3)$color <- "gray70"
E(und_subnetwork3)[(V(und_subnetwork3)$party == 'R') %--% (V(und_subnetwork3)$party == 'D')]$color <- "purple3"
deg3 <- igraph::degree(sub.network3, mode="all")
V(sub.network3)$deg3 <- deg3
par(mar = no_marg)
plot(
  und_subnetwork3,
  layout = layout_nicely(und_subnetwork3),
  vertex.size = deg3/2,
  vertex.frame.width = 3,
  vertex.label.cex = 0.5,
  vertex.label.family = "Helvetica",
  vertex.shape = "circle",
  vertex.label.color = V(und_subnetwork3)$label.color,
  edge.width = 2
)
```
```{r}
# Inter-chamber/Intra-chamber Interactions

# Color Chambers
V(und_subnetwork3)[V(und_subnetwork3)$chamber == "Senate"]$color <- "gold"
V(und_subnetwork3)[V(und_subnetwork3)$chamber == "House"]$color <- "dodgerblue"

# Color Party Leaders
V(und_subnetwork3)[V(und_subnetwork3)$congressperson %in% dem_leaders]$color <- "blue"
V(und_subnetwork3)[V(und_subnetwork3)$congressperson %in% rep_leaders]$color <- "red"

# Set Label Colors
V(und_subnetwork3)[V(und_subnetwork3)$chamber == "Senate"]$label.color <- "black"
V(und_subnetwork3)[V(und_subnetwork3)$chamber == "House"]$label.color <- "gray99"


# Set Edge Colors by Interaction
E(und_subnetwork3)$color <- "darkgreen"
E(und_subnetwork3)[(V(und_subnetwork3)$chamber == 'Senate') %--% (V(und_subnetwork2)$chamber == 'Senate')]$color <- "gold"
E(und_subnetwork3)[(V(und_subnetwork3)$chamber == 'House') %--% (V(und_subnetwork2)$chamber == 'House')]$color <- "lightskyblue"


par(mar = no_marg)
plot(
  und_subnetwork3,
  layout = layout_on_grid(und_subnetwork3),
  vertex.size = 7,
  vertex.label.cex = 0.65,
  vertex.label.family = "Helvetica",
  vertex.color = V( und_subnetwork3)$color,
  vertex.shape = "circle",
  vertex.frame.color = "gray50",
  vertex.label.color = V(und_subnetwork3)$label.color,
  edge.width = 1,
  edge.curved = 0.2,
)
```


```{r}
table(V(und_subnetwork3)$region)

regioncolors <- c('Midwest'='purple', 'Northeast'='pink', 'South'='skyblue', 'West'='gold')
regionlabels <- c('Midwest'='black', 'Northeast'='black', 'South'='black', 'West'='black')
V(und_subnetwork3)$color <- regioncolors[V(und_subnetwork3)$region]
V(und_subnetwork3)$frame.color <- regioncolors[V(und_subnetwork3)$region]
V(und_subnetwork3)$label.color <- regionlabels[V(und_subnetwork3)$region]

E(und_subnetwork3)$color <- "blue"
E(und_subnetwork3)[(V(und_subnetwork3)$region == 'Midwest') %--% (V(und_subnetwork3)$region == 'Midwest')]$color <- "purple"
E(und_subnetwork3)[(V(und_subnetwork3)$region == 'Northeast') %--% (V(und_subnetwork3)$region == 'Northeast')]$color <- "pink"
E(und_subnetwork3)[(V(und_subnetwork3)$region == 'South') %--% (V(und_subnetwork3)$region == 'South')]$color <- "skyblue"
E(und_subnetwork3)[(V(und_subnetwork3)$region == 'West') %--% (V(und_subnetwork3)$region == 'West')]$color <- "gold"

par(mar=no_marg)
plot(und_subnetwork3,
    layout=layout_in_circle(und_subnetwork3),
    vertex.size = 8,
    vertex.label.cex = 0.5,
    vertex.label.family = 'Helvetica',
    vertex.frame.color = V(und_subnetwork3)$color,
    vertex.label.color = V(und_subnetwork3)$label.color,
    edge.width = 1,
    edge.arrow.size = 0.1)
```
## Subgraph 4
```{r}
und_subnetwork4 <- as.undirected(sub.network4)
deg4 <- igraph::degree(sub.network4, mode="all")
V(sub.network4)$deg4 <- deg4

sen_maj_leader <- "Chuck Shumer"
sen_min_leader <- "Mitch McConnell"
house_speaker <- "Nancy Pelosi"
house_maj_leader <- "Steny Hoyer"
house_min_leader <- "Kevin McCarthy"

dem_leaders <- c(sen_maj_leader, house_speaker, house_min_leader)
rep_leaders <- c(sen_min_leader, house_min_leader)
leaders <- c(dem_leaders, rep_leaders)

# Intra-party Interactions
 
# Color Parties
V(und_subnetwork4)[V(und_subnetwork4)$party == 'R']$color <- "red"
V(und_subnetwork4)[V(und_subnetwork4)$party == 'D']$color <- "blue"
V(und_subnetwork4)[V(und_subnetwork4)$party == 'I']$color <- "yellow"

# Color Congressional Leaders
V(und_subnetwork4)[V(und_subnetwork4)$congressperson %in% leaders]$frame.color <- "gold"

# Label Colors
V(und_subnetwork4)[(V(und_subnetwork4)$party == 'R') | (V(und_subnetwork4)$party == 'D')]$label.color <- "white"
V(und_subnetwork4)[V(und_subnetwork4)$party == "I"]$label.color <- "black"

# Color Edges
E(und_subnetwork4)$color <- "gray70"
E(und_subnetwork4)[(V(und_subnetwork4)$party == 'R') %--% (V(und_subnetwork4)$party == 'D')]$color <- "purple3"

par(mar = no_marg)
plot(
  und_subnetwork4,
  layout = layout_with_kk(und_subnetwork4),
  vertex.size = deg4/2,
  vertex.frame.width = 3,
  vertex.label.cex = 0.8,
  vertex.label.family = "Helvetica",
  vertex.shape = "circle",
  vertex.label.color = V(und_subnetwork4)$label.color,
  edge.width = 2
)
```
```{r}
# Inter-chamber/Intra-chamber Interactions

# Color Chambers
V(und_subnetwork4)[V(und_subnetwork4)$chamber == "Senate"]$color <- "gold"
V(und_subnetwork4)[V(und_subnetwork4)$chamber == "House"]$color <- "dodgerblue"

# Color Party Leaders
V(und_subnetwork4)[V(und_subnetwork4)$congressperson %in% dem_leaders]$color <- "blue"
V(und_subnetwork4)[V(und_subnetwork4)$congressperson %in% rep_leaders]$color <- "red"

# Set Label Colors
V(und_subnetwork4)[V(und_subnetwork4)$chamber == "Senate"]$label.color <- "black"
V(und_subnetwork4)[V(und_subnetwork4)$chamber == "House"]$label.color <- "gray99"


# Set Edge Colors by Interaction
E(und_subnetwork4)$color <- "darkgreen"
E(und_subnetwork4)[(V(und_subnetwork4)$chamber == 'Senate') %--% (V(und_subnetwork4)$chamber == 'Senate')]$color <- "gold"
E(und_subnetwork4)[(V(und_subnetwork4)$chamber == 'House') %--% (V(und_subnetwork4)$chamber == 'House')]$color <- "lightskyblue"


par(mar = no_marg)
plot(
  und_subnetwork4,
  layout = layout_on_grid(und_subnetwork4),
  vertex.size = 7,
  vertex.label.cex = 0.65,
  vertex.label.family = "Helvetica",
  vertex.color = V(und_subnetwork4)$color,
  vertex.shape = "circle",
  vertex.frame.color = "gray50",
  vertex.label.color = V(und_subnetwork4)$label.color,
  edge.width = 1,
  edge.curved = 0.2,
)
```
```{r}
table(V(und_subnetwork4)$region)

regioncolors <- c('Midwest'='purple', 'Northeast'='pink', 'South'='skyblue', 'West'='gold')
regionlabels <- c('Midwest'='black', 'Northeast'='black', 'South'='black', 'West'='black')
V(und_subnetwork4)$color <- regioncolors[V(und_subnetwork4)$region]
V(und_subnetwork4)$frame.color <- regioncolors[V(und_subnetwork4)$region]
V(und_subnetwork4)$label.color <- regionlabels[V(und_subnetwork4)$region]

V(und_subnetwork4)$region[is.na(V(und_subnetwork4)$region)] <- "None"

E(und_subnetwork4)$color <- "blue"
E(und_subnetwork4)[(V(und_subnetwork4)$region == 'Midwest') %--% (V(und_subnetwork4)$region == 'Midwest')]$color <- "purple"
E(und_subnetwork4)[(V(und_subnetwork4)$region == 'Northeast') %--% (V(und_subnetwork4)$region == 'Northeast')]$color <- "pink"
E(und_subnetwork4)[(V(und_subnetwork4)$region == 'South') %--% (V(und_subnetwork4)$region == 'South')]$color <- "skyblue"
E(und_subnetwork4)[(V(und_subnetwork4)$region == 'West') %--% (V(und_subnetwork4)$region == 'West')]$color <- "gold"

par(mar=no_marg)
plot(und_subnetwork4,
    layout=layout_in_circle(und_subnetwork4),
    vertex.size = 8,
    vertex.label.cex = 0.5,
    vertex.label.family = 'Helvetica',
    vertex.frame.color = V(und_subnetwork4)$color,
    vertex.label.color = V(und_subnetwork4)$label.color,
    edge.width = 1,
    edge.arrow.size = 0.1)
```

# Network Metrics of Original Congress dataset
```{r}
deg_in = igraph::degree(congress_twi.igraph, mode='in') 
# the number of incoming edges connecting to each node
sort(deg_in, decreasing = T, index.return = T) 

# 323 has the most in degree
V(congress_twi.igraph)[323]$congressperson
V(congress_twi.igraph)[323]$chamber
V(congress_twi.igraph)[323]$state
V(congress_twi.igraph)[323]$party
# Kevin McCarthy, house of representatives from cali, a republicant
# house of representative 2007 to 2023 


sort(deg_in, decreasing = F, index.return = T) 
# 32 has the least in degree
V(congress_twi.igraph)[32]$congressperson
# Chuck Grassley 90 years old

deg_out = igraph::degree(congress_twi.igraph, mode='out') # the number of incoming edges connecting to each node
sort(deg_out, decreasing = T, index.return = T) 
V(congress_twi.igraph)[368]$congressperson 
# Nancy Pelosi has the most out degree

sort(deg_out, decreasing = F, index.return = T) 
# 396 has the least in degree
V(congress_twi.igraph)[396]$congressperson
# Gregoro Sablan 69 age
```

```{r}
mean_distance(congress_twi.igraph) #the average distance it takes for one node to reach other nodes

edge_density(congress_twi.igraph) # the proportion of actual edges out of the largest possible edges in the graph

reciprocity(congress_twi.igraph) # the ratio of the number of reciprocal edges over the total number of edges

transitivity(congress_twi.igraph) # the probability of nodes in triplet

diameter(congress_twi.igraph) #  the longest path between any pair of nodes in the graph

articulation_points(congress_twi.igraph) # the number of strongly connected subgroup within the graph
```

# Community Detection of Congress network
```{r}
und.congress <- as.undirected(congress_twi.igraph)
nc <- cluster_fast_greedy(und.congress)

sizes(nc)
modularity(nc)
membership(nc)
```

# Adjacency plot
```{r, fig.width=20, fig.height=20}
congress_twi.adjacency <- as_adj(congress_twi.igraph)
congress_twi.adjacency
image(congress_twi.adjacency, col.region=c('black'))
# can see the spread between senate and house
```

